### ISSUE TITLE
Bildinformationen 

### ISSUE THREAD

**Issue by Stricttype** [Stricttype/hga#10]
Die Bildinformationen funktionieren noch nicht. wenn ich auf info klicke passiert noch gar nichts.

**Comment by dl7vkj** [comment]
Sollte jetzt funktionieren. Die css aus dem gelaendesport.html-header bitte in die app.scss kopieren und übersetzen.

**Comment by Stricttype** [comment]
kann man die den slick slider so einstellen, dass er losgeht wenn die section im viewport ist?

**Comment by dl7vkj** [comment]
Jupp, erledigt
