### ISSUE TITLE
Animation Index seite

### ISSUE THREAD

**Issue by Stricttype** [Stricttype/hga#7]
Auf der Indexseite soll in der zweite <section> eine animation ablaufen. Wie eine Slideshow. Content und Markup habe ich schon eingesetzt. Mit dem fullpage.js Plugin kann man auch autoplay for horizontale slides einstellen. Mein Problem ist, dass die slides überblenden sollen und eine Farbige Fläche mit text infos versetzt über die Bilder blenden muss. Hast du eine Ahnung wie?
Ein Beispiel mit der Animation das ich in Adobe Edge Animate gebaut habe liegt im Ordner drin HGA-anim-Final-01.html Dort kann man sehen wie die Farbigen Flächen sich über dem Bild einblenden.
Es dauert ein wenig bis die animation startet.

**Comment by dl7vkj** [comment]
Das müsste doch mit Hilfe von CSS-Transitions gehen. Der aktive Slide bekommt ja irgendeine active-Klasse zugewiesen.  Und dann: .slide.active .text {.. show...} und .slide .text { ...hide...transition: all xxx...}. Mit CSS kannst Du die Größe, Deckkraft, Position, Drehung usw. ändern.
Schau Dir mal die Links an:
[Transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions)
[Transform](http://www.w3schools.com/cssref/css3_pr_transform.asp)
[Opacity](http://www.w3schools.com/cssref/css3_pr_opacity.asp)

**Comment by dl7vkj** [comment]
Wollte es nicht schließen...

**Comment by Stricttype** [comment]
yo das mit den transitions sollte klappen per css 3 klappen, aber die autoscrollfunktion von fullpage.js schiebt die seiten immer in der horizontalen. das kann ich per css3 nicht einstellen glaube ich.

**Comment by dl7vkj** [comment]
Habe den fullpage.js slider durch slick ersetzt. Letzterer wird auch von foundation empfohlen. Schau es dir einfach mal an.
