### ISSUE TITLE
Index (preloader)

### ISSUE THREAD

**Issue by Stricttype** [Stricttype/hga#8]
Können wir ein Preloader einbauen, so dass die Seite einblendet wenn der Aufbau und Content geladen ist?

**Comment by dl7vkj** [comment]
ja, das sollte einfach sein. Mit welchem Tool übersetzt Du die sass-Dateien?

**Comment by Stricttype** [comment]
codekit nennt sich das und ruby compiler. ich kann auch libsass einstellen, wenn das besser ist.

**Comment by dl7vkj** [comment]
Bekomme es bei nicht compiliert. codekit gibt es ned unter windows. Deshalb habe ich die styles einfach in die html-Dateien geschrieben. Die Seite blendet jetzt ein.
