### ISSUE TITLE
Gallery Lightbox

### ISSUE THREAD

**Issue by Stricttype** [Stricttype/hga#9]
Die Gallery lightbox soll sich wieder einschieben, wenn man von der dritten <section> zurück zur zweiten springt.

Außerdem scrollt noch der Main content mit wenn ich in der Lightbox mit dem Mausrad scrolle. Kann man das noch einstellen?

**Comment by dl7vkj** [comment]
Guck mal, ob es in Safarie auch gefixt ist.
